# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: scf.dalecarnegiemg.com.br
  email_provider_username: rafael@dalecarnegiemg.com.br
  email_provider_password: rsvas.2006L
  secret_key_base: e860e00e774538cbc7803f4dd6a221df9b19a41852ed6c97b8393ebbadda0d6a4be7cdc8bcd67322c512ed55ccbcf133821d2ba5c08ee1efacc00476879480c7

test:
  domain_name: example.com 
  secret_key_base: ee44164d29fab0b99d7f98271938353117e418bf8096a3e9982e137599f6d85fb95adcd4ccdd56d4e57afd2e815b2e127959088c9ffcaa473cca7c5be0a13c6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Rafael Spinola
  admin_email: rafael@dalecarnegiemg.com.br
  admin_password: 
  domain_name: scf.dalecarnegiemg.com.br
  secret_key_base: e860e00e774538cbc7803f4dd6a221df9b19a41852ed6c97b8393ebbadda0d6a4be7cdc8bcd67322c512ed55ccbcf133821d2ba5c08ee1efacc00476879480c7
  email_provider_username: rafael@dalecarnegiemg.com.br
  email_provider_password: rsvas.2006L
